### ISSUE TITLE
Conficting types for 'encrypt' 

### ISSUE THREAD

**Issue by ralphreijs** [AgentFeeble/pgoapi#10]
Hi @AgentFeeble !

I've cloned this repo and opened the example in Xcode 8.1 (8B62). After opening, it shows a few messages that Legacy Swift syntax has not been specified (has to be set to NO for Alamofire, Bolts-Swift and Protocol-Buffers, but after that has been set there is no problem compiling them). 

After succesfully building all components, I start building "Example". Before even getting to copying the encrypt-libs, i get an error "Conflicting Types for 'encrypt'" in encrypt.h.  

<img width="1277" alt="screen shot 2016-12-03 at 09 31 06" src="https://cloud.githubusercontent.com/assets/203897/20858048/a7daad48-b93b-11e6-86d5-8926f93d1f9c.png"><br><br>

The additional message is that there is a previous declaration. How do I solve this?

<img width="1280" alt="screen shot 2016-12-03 at 09 31 35" src="https://cloud.githubusercontent.com/assets/203897/20858049/a7fac8a8-b93b-11e6-838d-65a6ac111c13.png"><br><br>

Besides that (perhaps related) is the error that the Bridging Header can not be imported, but i'm looking into that still.

**Comment by AgentFeeble** [comment]
Hey @canphaz

I think the legacy Swift version stuff is because I used an older version of CocoaPods to install the dependencies. I'll update the project settings soon, thanks for letting me know about it.

The other issue looks quite strange because there is no method name `encrypt` in `encrypt.h`. I think the issue is that in your encrypt lib, the function is named `encrypt`, but needs to be named `encryptMethod`, as defined in `encrypt.h`. How did you import the encrypt lib, as code to be compiled by Xcode, or as a pre-compiled binary? If it's imported as code, can you try to rename the functions to match the declarations in `encrypt.h`and see if that works?
